apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeebe-broker
  namespace: zeebe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zeebe-broker
    spec:
      containers:
      - name: zeebe-broker
        image: docker.consulting.camunda.com/zeebe-configurable-host:latest
        ports:
        - containerPort: 51015
        - containerPort: 51016
        - containerPort: 51017
        volumeMounts:
        - mountPath: /usr/local/zeebe/data
          name: zeebe-data  
        env:
        - name: ZEEBE_HOST
          value: zeebe-api.zeebe
      volumes:
      - name: zeebe-data
        persistentVolumeClaim:
          claimName: zeebe-pvc
      imagePullSecrets:
      - name: regsecret          