apiVersion: v1
kind: Secret
data:
  .dockercfg: INDERT_HERE, see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ 
metadata:
  name: regsecret
  namespace: zeebe
  resourceVersion: "3739"
  selfLink: /api/v1/namespaces/default/secrets/regsecret
  uid: 1b2a3b15-82a3-11e7-88a1-42010a9a0fd5
type: kubernetes.io/dockercfg
