apiVersion: v1
kind: Service
metadata:
    name: zeebe-monitor-api
    namespace: zeebe
spec:
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
        name: web-api      
  selector:
      name: zeebe-monitor
  type: LoadBalancer