apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeebe-monitor
  namespace: zeebe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zeebe-monitor
    spec:
      containers:
      - name: zeebe-simple-monitor
        image: docker.consulting.camunda.com/zeebe-simple-monitor:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsecret